Document that the submodules need to be checked out before building
The error without checking out submodules is not obviously related to
the problem:
```
[ 42%] Building CXX object CMakeFiles/in-formant.dir/src/context/synthwrapper.cpp.o
In file included from /Users/jyn/src/in-formant/local/in-formant_autogen/mocs_compilation.cpp:2:
In file included from /Users/jyn/src/in-formant/local/in-formant_autogen/4TE63L34HC/moc_config.cpp:9:
/Users/jyn/src/in-formant/local/in-formant_autogen/4TE63L34HC/../../../src/context/config.h:7:10: fatal error: 'toml++/toml.h' file not found
 #include <toml++/toml.h>
         ^~~~~~~~~~~~~~~
```